# Generated by Django 3.0.7 on 2020-08-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pass_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
