# Generated by Django 3.0.3 on 2021-04-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210425_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Faculty'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Grade'),
        ),
    ]
