# Generated by Django 3.0.7 on 2020-08-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200811_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.TextField(default=0),
        ),
    ]
