# Generated by Django 3.0.3 on 2021-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210425_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='assignment_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='attendance_marks',
            field=models.IntegerField(default=0),
        ),
    ]
