# Generated by Django 3.0.7 on 2020-08-12 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_faculty_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='faculty_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Faculty'),
        ),
        migrations.AddField(
            model_name='marks',
            name='grade_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Grade'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='obtained_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
