# Generated by Django 3.0.7 on 2020-08-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200816_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course_id',
        ),
    ]
