# Generated by Django 3.0.7 on 2020-08-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20200820_2213'),
        ('students', '0012_auto_20200820_0854'),
    ]

    operations = [
    ]
