# Generated by Django 3.0.7 on 2020-08-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_merge_20200820_2254'),
        ('students', '0013_auto_20200820_2155'),
    ]

    operations = [
    ]
