# Generated by Django 3.1 on 2020-08-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20200820_2155'),
        ('students', '0013_merge_20200820_2254'),
    ]

    operations = [
    ]
