# Generated by Django 3.0.3 on 2020-08-22 05:05
# Generated by Django 3.1 on 2020-08-22 05:05
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_merge_20200820_2327'),
        ('students', '0014_merge_20200820_2328'),
        ('students', '0015_auto_20200821_0955'),
    ]

    operations = [
    ]
