# Generated by Django 3.1 on 2020-09-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20200831_1237'),
        ('students', '0018_auto_20200831_2056'),
    ]

    operations = [
    ]
