# Generated by Django 3.0.7 on 2020-09-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20200831_2056'),
        ('students', '0018_auto_20200831_1237'),
    ]

    operations = [
    ]
