# Generated by Django 3.1.1 on 2020-09-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_merge_20200902_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
