# Generated by Django 3.1.1 on 2020-09-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20200902_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='marks_id',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='term_id',
        ),
    ]
