# Generated by Django 3.1 on 2020-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20200902_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='terms_id',
            new_name='terms',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='grade_id',
        ),
        migrations.AddField(
            model_name='marks',
            name='course',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='marks',
            name='faculty',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='marks',
            name='grade',
            field=models.IntegerField(default=None),
        ),
    ]
