# Generated by Django 3.1.1 on 2020-09-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20200905_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentcourse',
            old_name='student_id',
            new_name='student',
        ),
    ]
