# Generated by Django 3.1.1 on 2020-09-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20200906_2203'),
        ('students', '0021_auto_20200906_2201'),
        ('students', '0019_merge_20200902_1029'),
    ]

    operations = [
    ]
