# Generated by Django 3.1.1 on 2020-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20200905_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='grade_id',
        ),
        migrations.AddField(
            model_name='marks',
            name='course',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='marks',
            name='faculty',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='marks',
            name='grade',
            field=models.IntegerField(default=None),
        ),
    ]
