# Generated by Django 3.1.1 on 2020-09-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_auto_20200905_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='terms_id',
            new_name='terms',
        ),
    ]
