# Generated by Django 3.0.3 on 2020-08-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinterface', '0002_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
