# Generated by Django 3.0.3 on 2020-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinterface', '0004_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Noo', max_length=255),
        ),
    ]
