# Generated by Django 3.0.3 on 2020-08-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinterface', '0005_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
