# Generated by Django 3.0.3 on 2020-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinterface', '0008_auto_20200820_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
