# Generated by Django 3.1.1 on 2020-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='file_upload',
            field=models.FileField(default=1, upload_to='files/pdfs/'),
        ),
    ]
