# Generated by Django 3.1.1 on 2020-09-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0002_postmessage_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmessage',
            name='file_upload',
            field=models.FileField(default=None, upload_to='files/pdfs/'),
        ),
    ]
