# Generated by Django 3.0.7 on 2020-08-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0003_auto_20200821_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
