# Generated by Django 3.0.7 on 2020-08-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0004_postmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='name',
            field=models.TextField(default=1),
        ),
    ]
