# Generated by Django 3.1.1 on 2020-09-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0004_postmessage_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmessage',
            name='image_upload',
        ),
    ]
