<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-08-31 06:52
=======
# Generated by Django 3.1 on 2020-08-31 06:43
>>>>>>> d585ac393c6839884fde36a1a147ffba368c2990

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0005_postmessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='image_id',
<<<<<<< HEAD
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacherinterface.Profile1'),
=======
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacherinterface.profile1'),
>>>>>>> d585ac393c6839884fde36a1a147ffba368c2990
        ),
    ]
