# Generated by Django 3.0.3 on 2020-09-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0006_auto_20200927_2248'),
        ('teacherinterface', '0002_postmessage'),
    ]

    operations = [
    ]
