# Generated by Django 3.1 on 2020-08-31 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0006_postmessage_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmessage',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherinterface.profile1'),
        ),
    ]
