# Generated by Django 3.1 on 2020-08-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0007_auto_20200831_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmessage',
            name='image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacherinterface.profile1'),
        ),
    ]
