# Generated by Django 3.0.7 on 2020-08-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0008_postmessage_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmessage',
            name='image_id',
        ),
    ]
