# Generated by Django 3.1 on 2020-08-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0008_auto_20200831_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmessage',
            old_name='image_id',
            new_name='picture_id',
        ),
    ]
