# Generated by Django 3.1 on 2020-08-31 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0010_remove_postmessage_picture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='picture_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacherinterface.profile1'),
        ),
    ]
