# Generated by Django 3.1 on 2020-09-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherinterface', '0009_remove_postmessage_image_id'),
        ('teacherinterface', '0012_remove_postmessage_picture_id'),
    ]

    operations = [
    ]
